apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.auth.image }}
          imagePullPolicy: Always
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "{{ .Values.auth.port }}"]
          ports:
            - containerPort: {{ .Values.auth.port }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.global.env.DB_HOST | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.global.env.DB_PORT | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.global.env.DB_NAME | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.global.env.DB_USER | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: postgres-password
            - name: REDIS_HOST
              value: {{ .Values.global.env.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.global.env.REDIS_PORT | quote }}
            - name: ALGORITHM
              value: {{ .Values.global.env.ALGORITHM | quote }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: secret-key
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auth.port }}
  selector:
    app: auth-service