apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
        - name: bff-service
          image: "{{ .Values.bff.image.repository }}:{{ .Values.bff.image.tag }}"
          imagePullPolicy: {{ .Values.bff.image.pullPolicy }}
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "{{ .Values.bff.port }}"]
          ports:
            - containerPort: {{ .Values.bff.port }}
          envFrom:
            - configMapRef:
                name: bff-config
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-password
                  name: team13-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: team13-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.bff.port }}
  selector:
    app: bff-service