apiVersion: apps/v1
kind: Deployment
metadata:
  name: habr-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habr-adapter
  template:
    metadata:
      labels:
        app: habr-adapter
    spec:
      containers:
        - name: habr-adapter
          image: "{{ .Values.habr.image.repository }}:{{ .Values.habr.image.tag }}"
          imagePullPolicy: {{ .Values.habr.image.pullPolicy }}
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "{{ .Values.habr.port }}"]
          ports:
            - containerPort: {{ .Values.habr.port }}
          env:
            - name: PROXY_URL
              valueFrom:
                secretKeyRef:
                  key: PROXY_URL
                  name: team13-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: {{ .Values.probes.http.healthPath | default "/health" }}
              port: {{ .Values.habr.port }}
            initialDelaySeconds: {{ .Values.probes.http.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.http.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.http.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.http.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.http.healthPath | default "/health" }}
              port: {{ .Values.habr.port }}
            initialDelaySeconds: {{ .Values.probes.http.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.http.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.http.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.http.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.http.healthPath | default "/health" }}
              port: {{ .Values.habr.port }}
            initialDelaySeconds: {{ .Values.probes.http.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.http.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.http.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.http.liveness.failureThreshold }} 
---
apiVersion: v1
kind: Service
metadata:
  name: habr-adapter
spec:
  ports:
    - port: {{ .Values.habr.port }}
  selector:
    app: habr-adapter