apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-consumer
  template:
    metadata:
      labels:
        app: llm-consumer
    spec:
      containers:
        - name: llm-consumer
          image: "{{ .Values.llm.image.repository }}:{{ .Values.llm.image.tag }}"
          imagePullPolicy: {{ .Values.llm.image.pullPolicy }}
          command: ["python", "consumer.py"]
          envFrom:
            - configMapRef:
                name: llm-consumer-config
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: team13-config
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: GEMINI_API_KEY
                  name: team13-config
            - name: PROXY_URL
              valueFrom:
                secretKeyRef:
                  key: PROXY_URL
                  name: team13-config
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  key: LLM_API_KEY
                  name: team13-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "ps aux | grep -v grep | grep consumer.py"
            initialDelaySeconds: {{ .Values.probes.exec.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.startup.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps aux | grep -v grep | grep consumer.py"
            initialDelaySeconds: {{ .Values.probes.exec.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.readiness.failureThreshold }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps aux | grep -v grep | grep consumer.py"
            initialDelaySeconds: {{ .Values.probes.exec.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.liveness.failureThreshold }} 