apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: {{ .Values.rabbitmq.port }}
            - containerPort: {{ .Values.rabbitmq.uiPort }}
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: team13-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: {{ .Values.probes.exec.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.startup.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: {{ .Values.probes.exec.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.readiness.failureThreshold }}
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: {{ .Values.probes.exec.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.liveness.failureThreshold }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.port }}
    - name: management
      port: {{ .Values.rabbitmq.uiPort }}
  selector:
    app: rabbitmq