apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: {{ .Values.rabbitmq.port }}
            - containerPort: {{ .Values.rabbitmq.uiPort }}
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: team13-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: {{ .Values.rabbitmq.probes.startup.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.rabbitmq.probes.startup.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.rabbitmq.probes.startup.timeoutSeconds | default 10 }}
            failureThreshold: {{ .Values.rabbitmq.probes.startup.failureThreshold | default 30 }}
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: {{ .Values.rabbitmq.probes.readiness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.rabbitmq.probes.readiness.periodSeconds | default 5 }}
            timeoutSeconds: {{ .Values.rabbitmq.probes.readiness.timeoutSeconds | default 10 }}
            failureThreshold: {{ .Values.rabbitmq.probes.readiness.failureThreshold | default 3 }}
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: {{ .Values.rabbitmq.probes.liveness.initialDelaySeconds | default 60 }}
            periodSeconds: {{ .Values.rabbitmq.probes.liveness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.rabbitmq.probes.liveness.timeoutSeconds | default 10 }}
            failureThreshold: {{ .Values.rabbitmq.probes.liveness.failureThreshold | default 3 }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.port }}
    - name: management
      port: {{ .Values.rabbitmq.uiPort }}
  selector:
    app: rabbitmq