apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.probes.exec.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.startup.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.probes.exec.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.readiness.failureThreshold }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.probes.exec.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.exec.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.exec.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.exec.liveness.failureThreshold }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    app: redis